<!DOCTYPE html>

<meta charset="utf-8">
<style>
    a {
        text-decoration: none !important;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<div class="container mt-3">
    <div class="row">
        <form method="get" class="col row">
            <input type="hidden" name="page" value="<?= $page ?>">
            <input type="hidden" name="perPage" value="<?= $perPage ?>"/>
            <input type="hidden" name="sortColumn" value="<?= $sortColumn ?>"/>
            <label for="searchQuery" class="col col-form-label">Список абитуриентов</label>
            <input type="search" id="searchQuery" name="searchQuery" class="col ms-3 form-control"
                   value="<?= $searchQuery ?>" autofocus>
            <button type="submit" class="col-auto ms-3 btn btn-primary">Найти</button>
        </form>

        <a href="register.php" role="button" class="col-auto ms-3 btn btn-primary">
            <?= isset($_COOKIE['student_hash']) ? "Изменить данные" : "Регистрация" ?>
        </a>
    </div>

    <table class="table mt-3">
        <thead>
        <th><a class="<?= ($sortColumn === 'name') ? 'text-primary' : 'text-body' ?>"
               href="<?= $pager->getLinkForPage($page, 'name') ?>">Имя</a></th>
        <th><a class="<?= ($sortColumn === 'surname') ? 'text-primary' : 'text-body' ?>"
               href="<?= $pager->getLinkForPage($page, 'surname') ?>">Фамилия</a></th>
        <th><a class="<?= ($sortColumn === 'group_number') ? 'text-primary' : 'text-body' ?>"
               href="<?= $pager->getLinkForPage($page, 'group_number') ?>">Номер группы</a></th>
        <th><a class="<?= ($sortColumn === 'points') ? 'text-primary' : 'text-body' ?>" href="<?= $sortByPointsLink ?>">Баллы</a>
        </th>
        </thead>
        <tbody>
        <?php if (isset($students)): ?>
            <?php foreach ($students as $student): ?>
                <tr>
                    <td>
                        <?= htmlspecialchars($student->name) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->surname) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->group_number) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->points) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <tr>
                <td colspan="4" class="text-center">Не найдено</td>
            </tr>
        <?php endif ?>
        </tbody>
    </table>

    <?php if ($pages > 1) : ?>
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link"
                       href="<?= $pager->getLinkForPage($page - 1, $sortColumn) ?>">
                        <span>&laquo;</span>
                    </a>
                </li>

                <?php for ($i = 1; $i <= $pages; $i++) : ?>
                    <li class="page-item <?= ($i === $page) ? 'active' : '' ?>">
                        <a class="page-link"
                           href="<?= $pager->getLinkForPage($i, $sortColumn) ?>"><?= $i ?></a>
                    </li>
                <?php endfor ?>

                <li class="page-item">
                    <a class="page-link"
                       href="<?= $pager->getLinkForPage($page + 1, $sortColumn) ?>">
                        <span>&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    <?php endif ?>
</div>