<!DOCTYPE html>

<meta charset="utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<div class="container">
    <?php if ($errors) : ?>
        <div class="alert alert-danger mt-3" role="alert">
            Не удалось добавить/изменить запись
        </div>
    <?php elseif ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
        <div class="alert alert-success mt-3" role="alert">
            Запись успешно добавлена/изменена
        </div>
    <?php endif ?>

    <div class="row mt-3">
        <a href="index.php" role="button" class="col col-auto ms-3 btn btn-primary">Список абитуриентов</a>
    </div>

    <form class="mt-5" method="POST">
        <div class="form-group row mb-3">
            <div class="col">
                <label for="name" class="form-label">Имя</label>
            </div>
            <div class="col">
                <input type="text" class="form-control <?= isset($errors['name']) ? 'is-invalid' : '' ?>" name="name"
                       minlength="1" maxlength="50" value="<?= $student->name ?? '' ?>">
                <?php if (isset($errors['name'])) : ?>
                    <div class="invalid-feedback"><?= $errors['name'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col">
                <label for="surname" class="form-label">Фамилия</label>
            </div>
            <div class="col">
                <input type="text" class="form-control <?= isset($errors['surname']) ? 'is-invalid' : '' ?>"
                       name="surname" minlength="1" maxlength="50" value="<?= $student->surname ?? '' ?>">
                <?php if (isset($errors['surname'])) : ?>
                    <div class="invalid-feedback"><?= $errors['surname'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col">
                <label for="group_number" class="form-label">Номер группы</label>
            </div>
            <div class="col">
                <input type="text" class="form-control <?= isset($errors['group_number']) ? 'is-invalid' : '' ?>"
                       name="group_number" minlength="1" maxlength="20"
                       value="<?= $student->group_number ?? '' ?>">
                <?php if (isset($errors['group_number'])) : ?>
                    <div class="invalid-feedback"><?= $errors['group_number'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col">
                <label for="points" class="form-label">Баллы</label>
            </div>
            <div class="col">
                <input type="number" class="form-control <?= isset($errors['points']) ? 'is-invalid' : '' ?>"
                       name="points" min="0" max="300" value="<?= $student->points ?? '' ?>">
                <?php if (isset($errors['points'])) : ?>
                    <div class="invalid-feedback"><?= $errors['points'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="row mb-3">
            <button class="btn btn-primary col-3 offset-9" type="submit">Отправить</button>
        </div>
    </form>


</div>