<!DOCTYPE html>

<meta charset="utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<div class="container">
    <div class="mt-3 row">
        <label for="searchQuery" class="col col-form-label">Список абитуриентов</label>
        <input type="search" class="col form-control mx-3" id="searchQuery">
        <button type="submit" class="col-auto btn btn-primary">Найти</button>
    </div>

    <table class="table mt-3">
        <thead>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Номер группы</th>
            <th>Баллы</th>
        </thead>
        <tbody>
            <?php if (isset($students)) : ?>
                <?php foreach ($students as $student) : ?>
                    <tr>
                        <td><?= htmlspecialchars($student->name) ?></td>
                        <td><?= htmlspecialchars($student->surname) ?></td>
                        <td><?= htmlspecialchars($student->group_number) ?></td>
                        <td><?= htmlspecialchars($student->points) ?></td>
                    </tr>
                <?php endforeach ?>
            <?php else : ?>
                <tr>
                    <td colspan="4" class="text-center">Не найдено</td>
                </tr>
            <?php endif ?>
        </tbody>
    </table>

    <form class="mt-5" action="../public/index.php" method="POST">
        <div class="form-group row mb-3">
            <div class="col">
                <label for="name" class="form-label">Имя</label>
            </div>
            <div class="col">
                <input type="text" class="form-control <?= isset($errors['name']) ? 'is-invalid' : '' ?>" name="name" minlength="1" maxlength="50" required>
                <?php if (isset($errors['name'])) : ?>
                    <div class="invalid-feedback"><?= $errors['name'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col">
                <label for="surname" class="form-label">Фамилия</label>
            </div>
            <div class="col">
                <input type="text" class="form-control <?= isset($errors['surname']) ? 'is-invalid' : '' ?>" name="surname" minlength="1" maxlength="50" required>
                <?php if (isset($errors['surname'])) : ?>
                    <div class="invalid-feedback"><?= $errors['surname'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col">
                <label for="group_number" class="form-label">Номер группы</label>
            </div>
            <div class="col">
                <input type="text" class="form-control <?= isset($errors['group_number']) ? 'is-invalid' : '' ?>" name="group_number" minlength="1" maxlength="20" required>
                <?php if (isset($errors['group_number'])) : ?>
                    <div class="invalid-feedback"><?= $errors['group_number'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="form-group row mb-3">
            <div class="col">
                <label for="points" class="form-label">Баллы</label>
            </div>
            <div class="col">
                <input type="number" class="form-control <?= isset($errors['points']) ? 'is-invalid' : '' ?>" name="points" min="0" max="300" required>
                <?php if (isset($errors['points'])) : ?>
                    <div class="invalid-feedback"><?= $errors['points'] ?></div>
                <?php endif ?>
            </div>
        </div>

        <div class="row mb-3">
            <button class="btn btn-primary col-3 offset-9" type="submit">Отправить</button>
        </div>
    </form>


</div>