<!DOCTYPE html>

<meta charset="utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<div class="container">
    <div class="row mt-3">
        <label for="searchQuery" class="col col-form-label">Список абитуриентов</label>
        <input type="search" id="searchQuery" class="col ms-3 form-control" autofocus>
        <button type="submit" class="col col-auto ms-3 btn btn-primary">Найти</button>
        <a href="register.php" role="button" class="col col-auto ms-3 btn btn-primary">Зарегистрироваться</a>
    </div>


    <table class="table mt-3">
        <thead>
            <th>ID</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Номер группы</th>
            <th>Баллы</th>
        </thead>
        <tbody>
            <?php if (isset($students)) : ?>
                <?php foreach ($students as $student) : ?>
                    <tr>
                        <td><?= htmlspecialchars($student->id) ?></td>
                        <td><?= htmlspecialchars($student->name) ?></td>
                        <td><?= htmlspecialchars($student->surname) ?></td>
                        <td><?= htmlspecialchars($student->group_number) ?></td>
                        <td><?= htmlspecialchars($student->points) ?></td>
                    </tr>
                <?php endforeach ?>
            <?php else : ?>
                <tr>
                    <td colspan="4" class="text-center">Не найдено</td>
                </tr>
            <?php endif ?>
        </tbody>
    </table>

    <nav>
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href=<?= $pager->getLinkForPage($page - 1, $perPage) ?> aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            <?php if ($pages > 1) : ?>
                <?php for ($i = 1; $i <= $pages; $i++) : ?>
                    <li class="page-item <?= ($i === $page) ? 'active' : '' ?>"><a class="page-link" href=<?= $pager->getLinkForPage($i, $perPage) ?>><?= $i ?></a></li>
                <?php endfor ?>
            <?php endif ?>

            <li class="page-item">
                <a class="page-link" href=<?= $pager->getLinkForPage($page + 1, $perPage) ?> aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>