<!DOCTYPE html>

<meta charset="utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<div class="container">
    <div class="row mt-3">
        <label for="searchQuery" class="col col-form-label">Список абитуриентов</label>
        <input type="search" id="searchQuery" class="col ms-3 form-control" autofocus>
        <button type="submit" class="col-auto ms-3 btn btn-primary">Найти</button>
        <a href="register.php" role="button" class="col-auto ms-3 btn btn-primary"><?= $btnMsg ?></a>
    </div>


    <p>
        your cookie hash: <?= $cookie_hash ?? 'none' ?>
    </p>

    <table class="table mt-3">
        <thead>
        <th>ID</th>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Номер группы</th>
        <th>Баллы</th>
        </thead>
        <tbody>
        <?php if (isset($students)): ?>
            <?php foreach ($students as $student): ?>
                <tr>
                    <td>
                        <?= htmlspecialchars($student->id) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->name) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->surname) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->group_number) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->points) ?>
                    </td>
                    <td>
                        <?= htmlspecialchars($student->hash) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <tr>
                <td colspan="4" class="text-center">Не найдено</td>
            </tr>
        <?php endif ?>
        </tbody>
    </table>

    <div class="btn-toolbar mb-3 justify-content-end" role="toolbar">
        <div class="input-group me-3">
            <div class="input-group-text">Страница</div>
            <input type="number" class="form-control" min="1" max="<? //= $pages ?>" value="<?= $page ?>">
            <div class="input-group-text">из <?= $pages ?></div>
        </div>
        <div class="btn-group" role="group">
            <a class="btn btn-outline-primary" href="<?= $prevPageLink ?>">
                &laquo;
            </a>
            <a class="btn btn-outline-primary" href="<?= $nextPageLink ?>">
                &raquo;
            </a>
        </div>
    </div>
</div>